fail_fast: true
#exclude: '^exclude'
repos:
  - repo: https://github.com/ambv/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: resources.py
        language_version: python3.10
  - repo: local
    hooks:
      - id: flake8-check1 # stop the build if there are Python syntax errors or undefined names
        name: flake8-check1
        entry: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=*exclude*
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: flake8-check2  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        name: flake8-check2
        entry: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=*exclude*
        language: system
        pass_filenames: false
        always_run: true
  - repo: local
    hooks:
      - id: compile-qt-resources
        name: compile-qt-resources
        entry: pyrcc5 -o resources.py resources.qrc
        language: system
        pass_filenames: false
        always_run: true