version: 1
disable_existing_loggers: True

formatters:
  standard:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  default:
    formatter: standard
    class: logging.StreamHandler
    stream: ext://sys.stderr

  pipeline_issues_file_handler:
    formatter: standard
    level: INFO
    class: logging.handlers.RotatingFileHandler
    filename: pipeline_issues.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

root:
  level: NOTSET
  handlers: [console]
  propagate: yes

loggers:
  sqlalchemy.x:
    handlers: [pipeline_issues_file_handler]
    level: WARNING
    propagate: yes

  ogr_convert:
    handlers: [pipeline_issues_file_handler]
    level: WARNING
    propagate: yes

  ogr_merge:
    handlers: [pipeline_issues_file_handler]
    level: WARNING
    propagate: yes

  google.auth.x:
    LEVEL: CRITICAL
    handlers: [pipeline_issues_file_handler]
    propagate: yes

  integration_ford:
    level: INFO
    handlers: [pipeline_issues_file_handler]
    propagate: yes

  integration_mapsindoors:
    level: INFO
    handlers: [pipeline_issues_file_handler]
    propagate: yes
