VERBOSE = False

ADD_GRAPH = True
ADD_DOORS = True

ONLY_SHOW_FIRST_FLOOR = True
ALLOW_LOCATION_CREATION = True

OSM_HIGHWAY_TYPES = {"footway": "footway", "elevator": "elevator", "steps": "steps"}
MAKE_HIGHWAY_TYPE_DROPDOWN = True
MAKE_LOCATION_TYPE_DROPDOWN = True
MAKE_DOOR_TYPE_DROPDOWN = True

ALLOW_DUPLICATE_VENUES_IN_PROJECT = False
SHOW_GRAPH_ON_LOAD = False

GENERATE_MISSING_EXTERNAL_IDS = False

HALF_SIZE = 0.5

MI_HIERARCHY_GROUP_NAME = "MapsIndoors (Database)"

SOLUTION_DESCRIPTOR = "(Solution)"
FLOOR_DESCRIPTOR = "(Floor)"
BUILDING_DESCRIPTOR = "(Building)"
VENUE_DESCRIPTOR = "(Venue)"
GRAPH_DESCRIPTOR = "(Graph)"

SOLUTION_DATA_DESCRIPTOR = "solution_data"
FLOOR_POLYGON_DESCRIPTOR = "floor_polygon"
BUILDING_POLYGON_DESCRIPTOR = "building_polygon"
VENUE_POLYGON_DESCRIPTOR = "venue_polygon"
NAVIGATION_LINES_DESCRIPTOR = "navigation_graph_lines"
NAVIGATION_POINT_DESCRIPTOR = "navigation_graph_points"
