VERBOSE = False

OSM_HIGHWAY_TYPES = {"footway": "footway", "elevator": "elevator", "steps": "steps"}

ALLOW_DUPLICATE_VENUES_IN_PROJECT = False
MAKE_FLOOR_WISE_LAYERS = False

ADD_STRING_NAN_CUSTOM_PROPERTY_VALUES = False
ADD_FLOAT_NAN_CUSTOM_PROPERTY_VALUES = False
ADD_REAL_NONE_CUSTOM_PROPERTY_VALUES = True

DEFAULT_CUSTOM_PROPERTIES = None

HALF_SIZE = 0.5
REAL_NONE_JSON_VALUE = "REAL_NONE"
NAN_VALUE = "nan"
NULL_VALUE = "NULL"
STR_NA_VALUE = "<NA>"

MI_HIERARCHY_GROUP_NAME = "MapsIndoors (Database)"

SOLUTION_DESCRIPTOR = "(Solution)"
FLOOR_DESCRIPTOR = "(Floor)"
BUILDING_DESCRIPTOR = "(Building)"
VENUE_DESCRIPTOR = "(Venue)"
GRAPH_DESCRIPTOR = "(Graph)"

SOLUTION_DATA_DESCRIPTOR = "solution_data"
FLOOR_POLYGON_DESCRIPTOR = "floor_polygon"
BUILDING_POLYGON_DESCRIPTOR = "building_polygon"
VENUE_POLYGON_DESCRIPTOR = "venue_polygon"
NAVIGATION_LINES_DESCRIPTOR = "graph_lines"
NAVIGATION_POINT_DESCRIPTOR = "graph_points"
DOORS_DESCRIPTOR = "doors"
CONNECTORS_DESCRIPTOR = "connectors"
HANDLE_OUTSIDE_FLOORS_SEPARATELY_FROM_BUILDINGS = False
