from .type_enums import BackendLocationTypeEnum

DATABASE_GROUP_DESCRIPTOR = "(Database) MapsIndoors"
SOLUTION_GROUP_DESCRIPTOR = "(Solution)"
FLOOR_GROUP_DESCRIPTOR = "(Floor)"
BUILDING_GROUP_DESCRIPTOR = "(Building)"
VENUE_GROUP_DESCRIPTOR = "(Venue)"
GRAPH_GROUP_DESCRIPTOR = "(Graph)"

OCCUPANTS_DESCRIPTOR = "occupants"
LOCATION_TYPE_DESCRIPTOR = "location_types"
SOLUTION_DATA_DESCRIPTOR = "solution_data"
DISPLAY_RULES_DESCRIPTOR = "display_rules"
APP_CONFIG_DESCRIPTOR = "app_config"
API_KEYS_DESCRIPTOR = "api_keys"
USER_ROLES = "user_roles"
FLOOR_POLYGON_DESCRIPTOR = "floor_polygon"
BUILDING_POLYGON_DESCRIPTOR = "building_polygon"
VENUE_POLYGON_DESCRIPTOR = "venue_polygon"

GRAPH_BOUND_DESCRIPTOR = "graph_bound"
NAVIGATION_HORIZONTAL_LINES_DESCRIPTOR = "horizontal_lines"
NAVIGATION_VERTICAL_LINES_DESCRIPTOR = "vertical_lines"
GRAPH_LINES_DESCRIPTOR = "graph_lines"
NAVIGATION_POINT_DESCRIPTOR = "graph_points"

ROOMS_DESCRIPTOR = BackendLocationTypeEnum.ROOM.value.lower()
AREAS_DESCRIPTOR = BackendLocationTypeEnum.AREA.value.lower()
POINT_OF_INTERESTS_DESCRIPTOR = BackendLocationTypeEnum.POI.value.lower()

LOCATION_DESCRIPTORS = (
    ROOMS_DESCRIPTOR,
    AREAS_DESCRIPTOR,
    POINT_OF_INTERESTS_DESCRIPTOR,
)

DOORS_GROUP_DESCRIPTOR = "(Doors)"
CONNECTORS_GROUP_DESCRIPTOR = "(Connectors)"
AVOIDS_GROUP_DESCRIPTOR = "(Avoids)"
PREFERS_GROUP_DESCRIPTOR = "(Prefers)"
BARRIERS_GROUP_DESCRIPTOR = "(Barriers)"
ENTRY_POINTS_GROUP_DESCRIPTOR = "(Entry Points)"
OBSTACLES_GROUP_DESCRIPTOR = "(Obstacles)"

ROUTE_ELEMENT_LAYER_DESCRIPTORS = [
    DOORS_GROUP_DESCRIPTOR,
    CONNECTORS_GROUP_DESCRIPTOR,
    AVOIDS_GROUP_DESCRIPTOR,
    PREFERS_GROUP_DESCRIPTOR,
    BARRIERS_GROUP_DESCRIPTOR,
    ENTRY_POINTS_GROUP_DESCRIPTOR,
    OBSTACLES_GROUP_DESCRIPTOR,
]
LAYER_DESCRIPTORS_WITH_TRANSLATIONS = [
    LOCATION_TYPE_DESCRIPTOR,
    FLOOR_POLYGON_DESCRIPTOR,
    BUILDING_POLYGON_DESCRIPTOR,
    VENUE_POLYGON_DESCRIPTOR,
    ROOMS_DESCRIPTOR,
    AREAS_DESCRIPTOR,
    POINT_OF_INTERESTS_DESCRIPTOR,
]
