VERBOSE = False
ADD_GRAPH = False
ADD_DOORS = False
ONLY_SHOW_FIRST_FLOOR = True
ALLOW_LOCATION_CREATION = True

CMS_HIERARCHY_GROUP_NAME = "CMS"

SOLUTION_DESCRIPTOR = "(Solution)"
FLOOR_DESCRIPTOR = "(Floor)"
BUILDING_DESCRIPTOR = "(Building)"
VENUE_DESCRIPTOR = "(Venue)"

SOLUTION_DATA_DESCRIPTOR = "solution_data"
FLOOR_POLYGON_DESCRIPTOR = "floor_polygon"
BUILDING_POLYGON_DESCRIPTOR = "building_polygon"
VENUE_POLYGON_DESCRIPTOR = "venue_polygon"
NAVIGATION_LINES_DESCRIPTOR = "navigation_graph_lines"
NAVIGATION_POINT_DESCRIPTOR = "navigation_graph_points"
