name: pr-package-plugin

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - os: ubuntu-latest
            platform: manylinux2014_x86_64
          - os: macos-latest
            platform: macosx_10_9_x86_64
          - os: windows-latest
            platform: win_amd64
          - os: macos-latest
            python-version: "3.9"
            platform: macosx_11_0_arm64

    if: github.repository_owner == 'MapsPeople'

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.CI_BOT_SSH_KEY }}
          #token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip qgis-plugin-ci jord

      - name: Package QGIS Plugin
        run: |
          python bundle_packaging.py --python_version ${{ matrix.python-version }} --plugin_version 0.0.1 --platform ${{ matrix.platform }}
          qgis-plugin-ci package 0.0.1 -a mi_companion_bundle

      #- name: Upload artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: mi_companion-${{ matrix.os }}-${{ matrix.python-version }}.zip
      #    path: mi_companion.0.0.1.zip

      - id: "auth"
        name: auth

        uses: "google-github-actions/auth@v2"
        with:
          project_id: "deployment-composer-test"
          workload_identity_provider: "projects/476136238084/locations/global/workloadIdentityPools/github/providers/mi-companion"
          service_account: point-inside-migration@deployment-composer-test.iam.gserviceaccount.com

      - id: "upload-file-to-bucket"
        name: upload-file-to-bucket
        uses: "google-github-actions/upload-cloud-storage@v2"
        with:
          path: mi_companion.0.0.1.zip
          destination: qgisplugins/dev/${{ matrix.platform }}/${{ matrix.python-version }}/

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
