on:
  push:
    tags:
      - "*"
  #release:
  #  types: published

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'automaps' && contains(github.ref, 'refs/tags/')

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
        #cache-dependency-path: "requirements/packaging.txt"

      #      - name: Install Qt lrelease
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get install qttools5-dev-tools
      #
      #      - name: Install Python requirements
      #        run: pip install -r requirements/packaging.txt

      - name: Install qgis-plugin-ci
        run: pip3 install qgis-plugin-ci

      - name: Fetch current changelog
        run: qgis-plugin-ci changelog ${{ env.RELEASE_VERSION }} >> release.md

      - name: Create release on GitHub
        uses: ncipollo/release-action@v1.14.0
        with:
          bodyFile: release.md
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy plugin
        run: >-
          qgis-plugin-ci
          release ${{ env.RELEASE_VERSION }}
          --github-token ${{ secrets.GITHUB_TOKEN }}
          --osgeo-username ${{ secrets.OSGEO_USER }}
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
          --create-plugin-repo

        #--transifex-token ${{ secrets.TRANSIFEX_TOKEN }}

      #      - name: Tweet
      #        uses: mugi111/tweet-trigger-release@v1.2
      #        with:
      #          consumer_key: ${{ secrets.TWITTER_CONSUMER_KEY }}
      #          consumer_secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
      #          access_token_key: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
      #          access_token_secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      #          tweet_body: "New version of plugin ${{ env.RELEASE_VERSION }}"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.CI_BOT_PAT }}
          repository: automaps/quiver
          event-type: merge-plugins
          client-payload: '{"name": "eqip", "version": "${{ env.RELEASE_VERSION }}", "url": "https://github.com/automaps/eqip/releases/latest/download/plugins.xml"}'
